
!$OPENAD XXX File_start [OAD_intrinsics.f90]
MODULE oad_intrinsics
use w2f__types
use OAD_active
IMPLICIT NONE
SAVE
!
!     **** Statements ****
!
END MODULE

C$OPENAD XXX File_start [all_globals_mod.f]
      MODULE all_globals_mod
      use w2f__types
      use OAD_active
      IMPLICIT NONE
      SAVE
C
C     **** Statements ****
C
      END MODULE
C#########################################################
C This file is part of OpenAD released under the LGPL.   #
C The full COPYRIGHT notice can be found in the top      #
C level directory of the OpenAD distribution             #
C#########################################################
C
C$OPENAD XXX File_start [head.f]
      SUBROUTINE head(X, F)
          use OAD_tape
          use OAD_rev

C original arguments get inserted before version
C         ! and declared here together with all local variables
C         ! generated by xaifBooster

      use w2f__types
      use OAD_active
      use oad_intrinsics
      use oad_intrinsics
      use oad_intrinsics
      IMPLICIT NONE
C
C     **** Global Variables & Derived Type Definitions ****
C
      INTEGER(w2f__i8) OpenAD_Symbol_135
      INTEGER(w2f__i8) OpenAD_Symbol_136
      INTEGER(w2f__i8) OpenAD_Symbol_137
      INTEGER(w2f__i8) OpenAD_Symbol_138
      INTEGER(w2f__i8) OpenAD_Symbol_139
      INTEGER(w2f__i8) OpenAD_Symbol_140
      REAL(w2f__8) OpenAD_acc_0
      REAL(w2f__8) OpenAD_acc_1
      REAL(w2f__8) OpenAD_acc_10
      REAL(w2f__8) OpenAD_acc_11
      REAL(w2f__8) OpenAD_acc_12
      REAL(w2f__8) OpenAD_acc_13
      REAL(w2f__8) OpenAD_acc_14
      REAL(w2f__8) OpenAD_acc_15
      REAL(w2f__8) OpenAD_acc_16
      REAL(w2f__8) OpenAD_acc_17
      REAL(w2f__8) OpenAD_acc_18
      REAL(w2f__8) OpenAD_acc_19
      REAL(w2f__8) OpenAD_acc_2
      REAL(w2f__8) OpenAD_acc_20
      REAL(w2f__8) OpenAD_acc_21
      REAL(w2f__8) OpenAD_acc_22
      REAL(w2f__8) OpenAD_acc_23
      REAL(w2f__8) OpenAD_acc_24
      REAL(w2f__8) OpenAD_acc_25
      REAL(w2f__8) OpenAD_acc_26
      REAL(w2f__8) OpenAD_acc_27
      REAL(w2f__8) OpenAD_acc_28
      REAL(w2f__8) OpenAD_acc_29
      REAL(w2f__8) OpenAD_acc_3
      REAL(w2f__8) OpenAD_acc_30
      REAL(w2f__8) OpenAD_acc_31
      REAL(w2f__8) OpenAD_acc_32
      REAL(w2f__8) OpenAD_acc_33
      REAL(w2f__8) OpenAD_acc_34
      REAL(w2f__8) OpenAD_acc_35
      REAL(w2f__8) OpenAD_acc_36
      REAL(w2f__8) OpenAD_acc_37
      REAL(w2f__8) OpenAD_acc_38
      REAL(w2f__8) OpenAD_acc_39
      REAL(w2f__8) OpenAD_acc_4
      REAL(w2f__8) OpenAD_acc_40
      REAL(w2f__8) OpenAD_acc_41
      REAL(w2f__8) OpenAD_acc_5
      REAL(w2f__8) OpenAD_acc_6
      REAL(w2f__8) OpenAD_acc_7
      REAL(w2f__8) OpenAD_acc_8
      REAL(w2f__8) OpenAD_acc_9
      type(active) :: OpenAD_prop_0
      type(active) :: OpenAD_prop_1
      type(active) :: OpenAD_prop_2
      type(active) :: OpenAD_prop_3
      type(active) :: OpenAD_prop_4
C
C     **** Parameters and Result ****
C
      type(active) :: X(1:9)
      type(active) :: F(1:7)
C
C     **** Local Variables and Functions ****
C
      REAL(w2f__8) H
      INTEGER(w2f__i4) I
      REAL(w2f__8) OpenAD_Symbol_1
      REAL(w2f__8) OpenAD_Symbol_100
      REAL(w2f__8) OpenAD_Symbol_101
      REAL(w2f__8) OpenAD_Symbol_102
      REAL(w2f__8) OpenAD_Symbol_103
      REAL(w2f__8) OpenAD_Symbol_105
      REAL(w2f__8) OpenAD_Symbol_106
      REAL(w2f__8) OpenAD_Symbol_107
      REAL(w2f__8) OpenAD_Symbol_108
      REAL(w2f__8) OpenAD_Symbol_110
      REAL(w2f__8) OpenAD_Symbol_111
      REAL(w2f__8) OpenAD_Symbol_114
      REAL(w2f__8) OpenAD_Symbol_115
      REAL(w2f__8) OpenAD_Symbol_116
      REAL(w2f__8) OpenAD_Symbol_117
      REAL(w2f__8) OpenAD_Symbol_118
      REAL(w2f__8) OpenAD_Symbol_119
      REAL(w2f__8) OpenAD_Symbol_12
      REAL(w2f__8) OpenAD_Symbol_121
      REAL(w2f__8) OpenAD_Symbol_122
      REAL(w2f__8) OpenAD_Symbol_125
      REAL(w2f__8) OpenAD_Symbol_127
      REAL(w2f__8) OpenAD_Symbol_128
      REAL(w2f__8) OpenAD_Symbol_129
      REAL(w2f__8) OpenAD_Symbol_130
      REAL(w2f__8) OpenAD_Symbol_131
      REAL(w2f__8) OpenAD_Symbol_133
      REAL(w2f__8) OpenAD_Symbol_134
      REAL(w2f__8) OpenAD_Symbol_14
      INTEGER(w2f__i8) OpenAD_Symbol_141
      INTEGER(w2f__i8) OpenAD_Symbol_142
      INTEGER(w2f__i8) OpenAD_Symbol_143
      INTEGER(w2f__i8) OpenAD_Symbol_144
      INTEGER(w2f__i8) OpenAD_Symbol_145
      INTEGER(w2f__i8) OpenAD_Symbol_146
      INTEGER(w2f__i8) OpenAD_Symbol_147
      INTEGER(w2f__i8) OpenAD_Symbol_148
      INTEGER(w2f__i8) OpenAD_Symbol_149
      REAL(w2f__8) OpenAD_Symbol_15
      INTEGER(w2f__i8) OpenAD_Symbol_150
      INTEGER(w2f__i8) OpenAD_Symbol_151
      INTEGER(w2f__i8) OpenAD_Symbol_152
      REAL(w2f__8) OpenAD_Symbol_153
      REAL(w2f__8) OpenAD_Symbol_154
      REAL(w2f__8) OpenAD_Symbol_155
      REAL(w2f__8) OpenAD_Symbol_156
      REAL(w2f__8) OpenAD_Symbol_157
      REAL(w2f__8) OpenAD_Symbol_158
      REAL(w2f__8) OpenAD_Symbol_159
      REAL(w2f__8) OpenAD_Symbol_16
      REAL(w2f__8) OpenAD_Symbol_160
      INTEGER(w2f__i8) OpenAD_Symbol_161
      REAL(w2f__8) OpenAD_Symbol_162
      REAL(w2f__8) OpenAD_Symbol_163
      REAL(w2f__8) OpenAD_Symbol_164
      REAL(w2f__8) OpenAD_Symbol_165
      INTEGER(w2f__i8) OpenAD_Symbol_166
      INTEGER(w2f__i8) OpenAD_Symbol_167
      INTEGER(w2f__i8) OpenAD_Symbol_168
      INTEGER(w2f__i8) OpenAD_Symbol_169
      REAL(w2f__8) OpenAD_Symbol_17
      INTEGER(w2f__i8) OpenAD_Symbol_170
      INTEGER(w2f__i8) OpenAD_Symbol_171
      REAL(w2f__8) OpenAD_Symbol_172
      REAL(w2f__8) OpenAD_Symbol_173
      REAL(w2f__8) OpenAD_Symbol_174
      REAL(w2f__8) OpenAD_Symbol_175
      INTEGER(w2f__i8) OpenAD_Symbol_176
      REAL(w2f__8) OpenAD_Symbol_177
      REAL(w2f__8) OpenAD_Symbol_178
      REAL(w2f__8) OpenAD_Symbol_179
      REAL(w2f__8) OpenAD_Symbol_18
      REAL(w2f__8) OpenAD_Symbol_180
      INTEGER(w2f__i8) OpenAD_Symbol_181
      INTEGER(w2f__i8) OpenAD_Symbol_182
      INTEGER(w2f__i8) OpenAD_Symbol_183
      INTEGER(w2f__i8) OpenAD_Symbol_184
      INTEGER(w2f__i8) OpenAD_Symbol_185
      INTEGER(w2f__i8) OpenAD_Symbol_186
      INTEGER(w2f__i8) OpenAD_Symbol_187
      REAL(w2f__8) OpenAD_Symbol_188
      REAL(w2f__8) OpenAD_Symbol_189
      REAL(w2f__8) OpenAD_Symbol_190
      REAL(w2f__8) OpenAD_Symbol_191
      REAL(w2f__8) OpenAD_Symbol_192
      REAL(w2f__8) OpenAD_Symbol_193
      REAL(w2f__8) OpenAD_Symbol_194
      REAL(w2f__8) OpenAD_Symbol_195
      REAL(w2f__8) OpenAD_Symbol_2
      REAL(w2f__8) OpenAD_Symbol_20
      REAL(w2f__8) OpenAD_Symbol_21
      REAL(w2f__8) OpenAD_Symbol_22
      REAL(w2f__8) OpenAD_Symbol_23
      REAL(w2f__8) OpenAD_Symbol_24
      REAL(w2f__8) OpenAD_Symbol_25
      REAL(w2f__8) OpenAD_Symbol_26
      REAL(w2f__8) OpenAD_Symbol_27
      REAL(w2f__8) OpenAD_Symbol_28
      REAL(w2f__8) OpenAD_Symbol_29
      REAL(w2f__8) OpenAD_Symbol_3
      REAL(w2f__8) OpenAD_Symbol_30
      REAL(w2f__8) OpenAD_Symbol_32
      REAL(w2f__8) OpenAD_Symbol_33
      REAL(w2f__8) OpenAD_Symbol_34
      REAL(w2f__8) OpenAD_Symbol_35
      REAL(w2f__8) OpenAD_Symbol_37
      REAL(w2f__8) OpenAD_Symbol_38
      REAL(w2f__8) OpenAD_Symbol_4
      REAL(w2f__8) OpenAD_Symbol_40
      REAL(w2f__8) OpenAD_Symbol_41
      REAL(w2f__8) OpenAD_Symbol_42
      REAL(w2f__8) OpenAD_Symbol_43
      REAL(w2f__8) OpenAD_Symbol_44
      REAL(w2f__8) OpenAD_Symbol_45
      REAL(w2f__8) OpenAD_Symbol_46
      REAL(w2f__8) OpenAD_Symbol_47
      REAL(w2f__8) OpenAD_Symbol_48
      REAL(w2f__8) OpenAD_Symbol_5
      REAL(w2f__8) OpenAD_Symbol_50
      REAL(w2f__8) OpenAD_Symbol_51
      REAL(w2f__8) OpenAD_Symbol_52
      REAL(w2f__8) OpenAD_Symbol_53
      REAL(w2f__8) OpenAD_Symbol_55
      REAL(w2f__8) OpenAD_Symbol_56
      REAL(w2f__8) OpenAD_Symbol_58
      REAL(w2f__8) OpenAD_Symbol_59
      REAL(w2f__8) OpenAD_Symbol_6
      REAL(w2f__8) OpenAD_Symbol_60
      REAL(w2f__8) OpenAD_Symbol_61
      REAL(w2f__8) OpenAD_Symbol_62
      REAL(w2f__8) OpenAD_Symbol_63
      REAL(w2f__8) OpenAD_Symbol_64
      REAL(w2f__8) OpenAD_Symbol_65
      REAL(w2f__8) OpenAD_Symbol_66
      REAL(w2f__8) OpenAD_Symbol_68
      REAL(w2f__8) OpenAD_Symbol_69
      REAL(w2f__8) OpenAD_Symbol_70
      REAL(w2f__8) OpenAD_Symbol_71
      REAL(w2f__8) OpenAD_Symbol_73
      REAL(w2f__8) OpenAD_Symbol_74
      REAL(w2f__8) OpenAD_Symbol_77
      REAL(w2f__8) OpenAD_Symbol_78
      REAL(w2f__8) OpenAD_Symbol_79
      REAL(w2f__8) OpenAD_Symbol_8
      REAL(w2f__8) OpenAD_Symbol_80
      REAL(w2f__8) OpenAD_Symbol_81
      REAL(w2f__8) OpenAD_Symbol_82
      REAL(w2f__8) OpenAD_Symbol_83
      REAL(w2f__8) OpenAD_Symbol_84
      REAL(w2f__8) OpenAD_Symbol_85
      REAL(w2f__8) OpenAD_Symbol_87
      REAL(w2f__8) OpenAD_Symbol_88
      REAL(w2f__8) OpenAD_Symbol_89
      REAL(w2f__8) OpenAD_Symbol_9
      REAL(w2f__8) OpenAD_Symbol_90
      REAL(w2f__8) OpenAD_Symbol_92
      REAL(w2f__8) OpenAD_Symbol_93
      REAL(w2f__8) OpenAD_Symbol_95
      REAL(w2f__8) OpenAD_Symbol_96
      REAL(w2f__8) OpenAD_Symbol_97
      REAL(w2f__8) OpenAD_Symbol_98
      REAL(w2f__8) OpenAD_Symbol_99


          integer iaddr
          external iaddr
C
C     **** Top Level Pragmas ****
C
C$OPENAD INDEPENDENT(X)
C$OPENAD DEPENDENT(F)
C
C     **** Statements ****
C

         if (our_rev_mode%plain) then
C original function
C$OPENAD XXX Template ad_template.f
      H = 2.5D-01
      F(1)%v = (X(1)%v*(-2.0D00)+((X(8)%v*H*H)/1.2D+01)*(EXP(X(1)%v/(X(1
     +)%v*X(9)%v+1.0D00))*1.0D+01+1.0D00))
      F(2)%v = (X(1)%v+EXP(X(1)%v/(X(1)%v*X(9)%v+1.0D00))*((X(8)%v*H*H)/
     +1.2D+01))
      DO I = 2,6,1
        F(INT(I+(-1)))%v = (X(I)%v+F(I+(-1))%v+EXP(X(I)%v/(X(I)%v*X(9)%v
     ++1.0D00))*((X(8)%v*H*H)/1.2D+01))
        F(INT(I))%v = (EXP(X(I)%v/(X(I)%v*X(9)%v+1.0D00))*((X(8)%v*H*H)/
     +1.19999999999999995559D00)+F(I)%v-X(I)%v*2.0D00)
        F(INT(I+1))%v = (X(I)%v+EXP(X(I)%v/(X(I)%v*X(9)%v+1.0D00))*((X(8
     +)%v*H*H)/1.2D+01))
      END DO
      F(6)%v = (X(7)%v+F(6)%v+EXP(X(7)%v/(X(7)%v*X(9)%v+1.0D00))*((X(8)%
     +v*H*H)/1.2D+01))
      F(7)%v = (F(7)%v-X(7)%v*2.0D00)
      F(7)%v = (F(7)%v+((X(8)%v*H*H)/1.2D+01)*(EXP(X(7)%v/(X(7)%v*X(9)%v
     ++1.0D00))*1.0D+01+1.0D00))
          end if
          if (our_rev_mode%tape) then
C taping
C$OPENAD XXX Template ad_template.f
      H = 2.5D-01
      OpenAD_Symbol_8 = (H*H)
      OpenAD_Symbol_5 = (X(8)%v*OpenAD_Symbol_8)
      OpenAD_Symbol_1 = (OpenAD_Symbol_5/1.2D+01)
      OpenAD_Symbol_16 = (X(1)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_14 = (X(1)%v/OpenAD_Symbol_16)
      OpenAD_Symbol_12 = EXP(OpenAD_Symbol_14)
      OpenAD_Symbol_2 = (OpenAD_Symbol_12*1.0D+01+1.0D00)
      F(1)%v = (X(1)%v*(-2.0D00)+OpenAD_Symbol_1*OpenAD_Symbol_2)
      OpenAD_Symbol_9 = OpenAD_Symbol_8
      OpenAD_Symbol_6 = (INT(1_w2f__i8)/1.2D+01)
      OpenAD_Symbol_3 = OpenAD_Symbol_2
      OpenAD_Symbol_17 = (INT(1_w2f__i8)/OpenAD_Symbol_16)
      OpenAD_Symbol_20 = X(9)%v
      OpenAD_Symbol_21 = X(1)%v
      OpenAD_Symbol_18 = (-(X(1)%v/(OpenAD_Symbol_16*OpenAD_Symbol_16)))
      OpenAD_Symbol_15 = EXP(OpenAD_Symbol_14)
      OpenAD_Symbol_4 = OpenAD_Symbol_1
      OpenAD_acc_0 = (OpenAD_Symbol_15*1.0D+01)
      OpenAD_acc_1 = (OpenAD_Symbol_9*OpenAD_Symbol_6*OpenAD_Symbol_3)
      OpenAD_acc_2 = (OpenAD_Symbol_17*OpenAD_acc_0*OpenAD_Symbol_4)
      OpenAD_acc_3 = (OpenAD_Symbol_18*OpenAD_acc_0*OpenAD_Symbol_4)
      OpenAD_acc_4 = (OpenAD_Symbol_20*OpenAD_acc_3)
      OpenAD_acc_5 = (OpenAD_Symbol_21*OpenAD_acc_3)
      double_tape(double_tape_pointer) = OpenAD_acc_1
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_2
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_4
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_5
      double_tape_pointer = double_tape_pointer+1
      OpenAD_Symbol_28 = (X(1)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_26 = (X(1)%v/OpenAD_Symbol_28)
      OpenAD_Symbol_22 = EXP(OpenAD_Symbol_26)
      OpenAD_Symbol_37 = (H*H)
      OpenAD_Symbol_34 = (X(8)%v*OpenAD_Symbol_37)
      OpenAD_Symbol_23 = (OpenAD_Symbol_34/1.2D+01)
      F(2)%v = (X(1)%v+OpenAD_Symbol_22*OpenAD_Symbol_23)
      OpenAD_Symbol_29 = (INT(1_w2f__i8)/OpenAD_Symbol_28)
      OpenAD_Symbol_32 = X(9)%v
      OpenAD_Symbol_33 = X(1)%v
      OpenAD_Symbol_30 = (-(X(1)%v/(OpenAD_Symbol_28*OpenAD_Symbol_28)))
      OpenAD_Symbol_27 = EXP(OpenAD_Symbol_26)
      OpenAD_Symbol_24 = OpenAD_Symbol_23
      OpenAD_Symbol_38 = OpenAD_Symbol_37
      OpenAD_Symbol_35 = (INT(1_w2f__i8)/1.2D+01)
      OpenAD_Symbol_25 = OpenAD_Symbol_22
      OpenAD_acc_6 = (OpenAD_Symbol_27*OpenAD_Symbol_24)
      OpenAD_acc_7 = (OpenAD_Symbol_38*OpenAD_Symbol_35*OpenAD_Symbol_25
     +)
      OpenAD_acc_8 = (OpenAD_Symbol_29*OpenAD_acc_6)
      OpenAD_acc_9 = (OpenAD_Symbol_30*OpenAD_acc_6)
      OpenAD_acc_10 = (OpenAD_Symbol_32*OpenAD_acc_9)
      OpenAD_acc_11 = (OpenAD_Symbol_33*OpenAD_acc_9)
      double_tape(double_tape_pointer) = OpenAD_acc_7
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_8
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_10
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_11
      double_tape_pointer = double_tape_pointer+1
      OpenAD_Symbol_137 = 0_w2f__i8
      DO I = 2,6,1
        OpenAD_Symbol_46 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_44 = (X(I)%v/OpenAD_Symbol_46)
        OpenAD_Symbol_40 = EXP(OpenAD_Symbol_44)
        OpenAD_Symbol_55 = (H*H)
        OpenAD_Symbol_52 = (X(8)%v*OpenAD_Symbol_55)
        OpenAD_Symbol_41 = (OpenAD_Symbol_52/1.2D+01)
        F(INT(I+(-1)))%v = (X(I)%v+F(I+(-1))%v+OpenAD_Symbol_40*OpenAD_S
     +ymbol_41)
        OpenAD_Symbol_47 = (INT(1_w2f__i8)/OpenAD_Symbol_46)
        OpenAD_Symbol_50 = X(9)%v
        OpenAD_Symbol_51 = X(I)%v
        OpenAD_Symbol_48 = (-(X(I)%v/(OpenAD_Symbol_46*OpenAD_Symbol_46)
     +))
        OpenAD_Symbol_45 = EXP(OpenAD_Symbol_44)
        OpenAD_Symbol_42 = OpenAD_Symbol_41
        OpenAD_Symbol_56 = OpenAD_Symbol_55
        OpenAD_Symbol_53 = (INT(1_w2f__i8)/1.2D+01)
        OpenAD_Symbol_43 = OpenAD_Symbol_40
        OpenAD_acc_12 = (OpenAD_Symbol_45*OpenAD_Symbol_42)
        OpenAD_acc_13 = (OpenAD_Symbol_56*OpenAD_Symbol_53*OpenAD_Symbol
     +_43)
        OpenAD_acc_14 = (OpenAD_Symbol_47*OpenAD_acc_12)
        OpenAD_acc_15 = (OpenAD_Symbol_48*OpenAD_acc_12)
        OpenAD_acc_16 = (OpenAD_Symbol_50*OpenAD_acc_15)
        OpenAD_acc_17 = (OpenAD_Symbol_51*OpenAD_acc_15)
        OpenAD_Symbol_141 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_141
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_142 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_142
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_143 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_143
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_13
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_144 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_144
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_14
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_145 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_145
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_16
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_146 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_146
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_17
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_147 = (I+(-1))
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_147
        integer_tape_pointer = integer_tape_pointer+1
        integer_tape(integer_tape_pointer) = I
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_64 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_62 = (X(I)%v/OpenAD_Symbol_64)
        OpenAD_Symbol_58 = EXP(OpenAD_Symbol_62)
        OpenAD_Symbol_73 = (H*H)
        OpenAD_Symbol_70 = (X(8)%v*OpenAD_Symbol_73)
        OpenAD_Symbol_59 = (OpenAD_Symbol_70/1.19999999999999995559D00)
        F(INT(I))%v = (OpenAD_Symbol_58*OpenAD_Symbol_59+F(I)%v-X(I)%v*2
     +.0D00)
        OpenAD_Symbol_65 = (INT(1_w2f__i8)/OpenAD_Symbol_64)
        OpenAD_Symbol_68 = X(9)%v
        OpenAD_Symbol_69 = X(I)%v
        OpenAD_Symbol_66 = (-(X(I)%v/(OpenAD_Symbol_64*OpenAD_Symbol_64)
     +))
        OpenAD_Symbol_63 = EXP(OpenAD_Symbol_62)
        OpenAD_Symbol_60 = OpenAD_Symbol_59
        OpenAD_Symbol_74 = OpenAD_Symbol_73
        OpenAD_Symbol_71 = (INT(1_w2f__i8)/1.19999999999999995559D00)
        OpenAD_Symbol_61 = OpenAD_Symbol_58
        OpenAD_acc_18 = (OpenAD_Symbol_63*OpenAD_Symbol_60)
        OpenAD_acc_19 = (OpenAD_Symbol_74*OpenAD_Symbol_71*OpenAD_Symbol
     +_61)
        OpenAD_acc_20 = (OpenAD_Symbol_65*OpenAD_acc_18)
        OpenAD_acc_21 = (OpenAD_Symbol_66*OpenAD_acc_18)
        OpenAD_acc_22 = (OpenAD_Symbol_68*OpenAD_acc_21)
        OpenAD_acc_23 = (OpenAD_Symbol_69*OpenAD_acc_21)
        double_tape(double_tape_pointer) = OpenAD_acc_19
        double_tape_pointer = double_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_20
        double_tape_pointer = double_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_22
        double_tape_pointer = double_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_23
        double_tape_pointer = double_tape_pointer+1
        integer_tape(integer_tape_pointer) = I
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_83 = (X(I)%v*X(9)%v+1.0D00)
        OpenAD_Symbol_81 = (X(I)%v/OpenAD_Symbol_83)
        OpenAD_Symbol_77 = EXP(OpenAD_Symbol_81)
        OpenAD_Symbol_92 = (H*H)
        OpenAD_Symbol_89 = (X(8)%v*OpenAD_Symbol_92)
        OpenAD_Symbol_78 = (OpenAD_Symbol_89/1.2D+01)
        F(INT(I+1))%v = (X(I)%v+OpenAD_Symbol_77*OpenAD_Symbol_78)
        OpenAD_Symbol_84 = (INT(1_w2f__i8)/OpenAD_Symbol_83)
        OpenAD_Symbol_87 = X(9)%v
        OpenAD_Symbol_88 = X(I)%v
        OpenAD_Symbol_85 = (-(X(I)%v/(OpenAD_Symbol_83*OpenAD_Symbol_83)
     +))
        OpenAD_Symbol_82 = EXP(OpenAD_Symbol_81)
        OpenAD_Symbol_79 = OpenAD_Symbol_78
        OpenAD_Symbol_93 = OpenAD_Symbol_92
        OpenAD_Symbol_90 = (INT(1_w2f__i8)/1.2D+01)
        OpenAD_Symbol_80 = OpenAD_Symbol_77
        OpenAD_acc_24 = (OpenAD_Symbol_82*OpenAD_Symbol_79)
        OpenAD_acc_25 = (OpenAD_Symbol_93*OpenAD_Symbol_90*OpenAD_Symbol
     +_80)
        OpenAD_acc_26 = (OpenAD_Symbol_84*OpenAD_acc_24)
        OpenAD_acc_27 = (OpenAD_Symbol_85*OpenAD_acc_24)
        OpenAD_acc_28 = (OpenAD_Symbol_87*OpenAD_acc_27)
        OpenAD_acc_29 = (OpenAD_Symbol_88*OpenAD_acc_27)
        OpenAD_Symbol_148 = (I+1)
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_148
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_25
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_149 = (I+1)
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_149
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_26
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_150 = (I+1)
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_150
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_28
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_151 = (I+1)
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_151
        integer_tape_pointer = integer_tape_pointer+1
        double_tape(double_tape_pointer) = OpenAD_acc_29
        double_tape_pointer = double_tape_pointer+1
        OpenAD_Symbol_152 = (I+1)
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_152
        integer_tape_pointer = integer_tape_pointer+1
        integer_tape(integer_tape_pointer) = I
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_137 = (INT(OpenAD_Symbol_137)+INT(1_w2f__i8))
      END DO
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_137
      integer_tape_pointer = integer_tape_pointer+1
      OpenAD_Symbol_101 = (X(7)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_99 = (X(7)%v/OpenAD_Symbol_101)
      OpenAD_Symbol_95 = EXP(OpenAD_Symbol_99)
      OpenAD_Symbol_110 = (H*H)
      OpenAD_Symbol_107 = (X(8)%v*OpenAD_Symbol_110)
      OpenAD_Symbol_96 = (OpenAD_Symbol_107/1.2D+01)
      F(6)%v = (X(7)%v+F(6)%v+OpenAD_Symbol_95*OpenAD_Symbol_96)
      OpenAD_Symbol_102 = (INT(1_w2f__i8)/OpenAD_Symbol_101)
      OpenAD_Symbol_105 = X(9)%v
      OpenAD_Symbol_106 = X(7)%v
      OpenAD_Symbol_103 = (-(X(7)%v/(OpenAD_Symbol_101*OpenAD_Symbol_101
     +)))
      OpenAD_Symbol_100 = EXP(OpenAD_Symbol_99)
      OpenAD_Symbol_97 = OpenAD_Symbol_96
      OpenAD_Symbol_111 = OpenAD_Symbol_110
      OpenAD_Symbol_108 = (INT(1_w2f__i8)/1.2D+01)
      OpenAD_Symbol_98 = OpenAD_Symbol_95
      OpenAD_acc_30 = (OpenAD_Symbol_100*OpenAD_Symbol_97)
      OpenAD_acc_31 = (OpenAD_Symbol_111*OpenAD_Symbol_108*OpenAD_Symbol
     +_98)
      OpenAD_acc_32 = (OpenAD_Symbol_102*OpenAD_acc_30)
      OpenAD_acc_33 = (OpenAD_Symbol_103*OpenAD_acc_30)
      OpenAD_acc_34 = (OpenAD_Symbol_105*OpenAD_acc_33)
      OpenAD_acc_35 = (OpenAD_Symbol_106*OpenAD_acc_33)
      double_tape(double_tape_pointer) = OpenAD_acc_31
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_32
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_34
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_35
      double_tape_pointer = double_tape_pointer+1
      F(7)%v = (F(7)%v-X(7)%v*2.0D00)
      OpenAD_Symbol_121 = (H*H)
      OpenAD_Symbol_118 = (X(8)%v*OpenAD_Symbol_121)
      OpenAD_Symbol_114 = (OpenAD_Symbol_118/1.2D+01)
      OpenAD_Symbol_129 = (X(7)%v*X(9)%v+1.0D00)
      OpenAD_Symbol_127 = (X(7)%v/OpenAD_Symbol_129)
      OpenAD_Symbol_125 = EXP(OpenAD_Symbol_127)
      OpenAD_Symbol_115 = (OpenAD_Symbol_125*1.0D+01+1.0D00)
      F(7)%v = (F(7)%v+OpenAD_Symbol_114*OpenAD_Symbol_115)
      OpenAD_Symbol_122 = OpenAD_Symbol_121
      OpenAD_Symbol_119 = (INT(1_w2f__i8)/1.2D+01)
      OpenAD_Symbol_116 = OpenAD_Symbol_115
      OpenAD_Symbol_130 = (INT(1_w2f__i8)/OpenAD_Symbol_129)
      OpenAD_Symbol_133 = X(9)%v
      OpenAD_Symbol_134 = X(7)%v
      OpenAD_Symbol_131 = (-(X(7)%v/(OpenAD_Symbol_129*OpenAD_Symbol_129
     +)))
      OpenAD_Symbol_128 = EXP(OpenAD_Symbol_127)
      OpenAD_Symbol_117 = OpenAD_Symbol_114
      OpenAD_acc_36 = (OpenAD_Symbol_128*1.0D+01)
      OpenAD_acc_37 = (OpenAD_Symbol_122*OpenAD_Symbol_119*OpenAD_Symbol
     +_116)
      OpenAD_acc_38 = (OpenAD_Symbol_130*OpenAD_acc_36*OpenAD_Symbol_117
     +)
      OpenAD_acc_39 = (OpenAD_Symbol_131*OpenAD_acc_36*OpenAD_Symbol_117
     +)
      OpenAD_acc_40 = (OpenAD_Symbol_133*OpenAD_acc_39)
      OpenAD_acc_41 = (OpenAD_Symbol_134*OpenAD_acc_39)
      double_tape(double_tape_pointer) = OpenAD_acc_37
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_38
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_40
      double_tape_pointer = double_tape_pointer+1
      double_tape(double_tape_pointer) = OpenAD_acc_41
      double_tape_pointer = double_tape_pointer+1
          end if
          if (our_rev_mode%adjoint) then
C adjoint
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_188 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_189 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_190 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_191 = double_tape(double_tape_pointer)
      X(9)%d = X(9)%d+F(7)%d*(OpenAD_Symbol_188)
      X(7)%d = X(7)%d+F(7)%d*(OpenAD_Symbol_189)
      X(7)%d = X(7)%d+F(7)%d*(OpenAD_Symbol_190)
      X(8)%d = X(8)%d+F(7)%d*(OpenAD_Symbol_191)
      OpenAD_prop_4%d = OpenAD_prop_4%d+F(7)%d
      F(7)%d = 0.0d0
      F(7)%d = F(7)%d+OpenAD_prop_4%d
      OpenAD_prop_4%d = 0.0d0
      X(7)%d = X(7)%d+F(7)%d*(-2.0D00)
      OpenAD_prop_3%d = OpenAD_prop_3%d+F(7)%d
      F(7)%d = 0.0d0
      F(7)%d = F(7)%d+OpenAD_prop_3%d
      OpenAD_prop_3%d = 0.0d0
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_192 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_193 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_194 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_195 = double_tape(double_tape_pointer)
      X(9)%d = X(9)%d+F(6)%d*(OpenAD_Symbol_192)
      X(7)%d = X(7)%d+F(6)%d*(OpenAD_Symbol_193)
      X(7)%d = X(7)%d+F(6)%d*(OpenAD_Symbol_194)
      X(8)%d = X(8)%d+F(6)%d*(OpenAD_Symbol_195)
      OpenAD_prop_2%d = OpenAD_prop_2%d+F(6)%d
      X(7)%d = X(7)%d+F(6)%d
      F(6)%d = 0.0d0
      F(6)%d = F(6)%d+OpenAD_prop_2%d
      OpenAD_prop_2%d = 0.0d0
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_135 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_136 = 1
      do while (INT(OpenAD_Symbol_136).LE.INT(OpenAD_Symbol_135))
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_161 = integer_tape(integer_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_162 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_163 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_164 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_165 = double_tape(double_tape_pointer)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_166 = integer_tape(integer_tape_pointer)
        X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_166))%d*(OpenAD_Symbol_162)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_167 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_161))%d = X(INT(OpenAD_Symbol_161))%d+F(INT(
     +OpenAD_Symbol_167))%d*(OpenAD_Symbol_163)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_168 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_161))%d = X(INT(OpenAD_Symbol_161))%d+F(INT(
     +OpenAD_Symbol_168))%d*(OpenAD_Symbol_164)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_169 = integer_tape(integer_tape_pointer)
        X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_169))%d*(OpenAD_Symbol_165)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_170 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_161))%d = X(INT(OpenAD_Symbol_161))%d+F(INT(
     +OpenAD_Symbol_170))%d
        F(INT(OpenAD_Symbol_170))%d = 0.0d0
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_171 = integer_tape(integer_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_172 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_173 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_174 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_175 = double_tape(double_tape_pointer)
        X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_171))%d*(OpenAD_Symbol_172)
        X(INT(OpenAD_Symbol_171))%d = X(INT(OpenAD_Symbol_171))%d+F(INT(
     +OpenAD_Symbol_171))%d*(OpenAD_Symbol_173)
        X(INT(OpenAD_Symbol_171))%d = X(INT(OpenAD_Symbol_171))%d+F(INT(
     +OpenAD_Symbol_171))%d*(OpenAD_Symbol_174)
        X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_171))%d*(OpenAD_Symbol_175)
        X(INT(OpenAD_Symbol_171))%d = X(INT(OpenAD_Symbol_171))%d+F(INT(
     +OpenAD_Symbol_171))%d*(-2.0D00)
        OpenAD_prop_1%d = OpenAD_prop_1%d+F(INT(OpenAD_Symbol_171))%d
        F(INT(OpenAD_Symbol_171))%d = 0.0d0
        F(INT(OpenAD_Symbol_171))%d = F(INT(OpenAD_Symbol_171))%d+OpenAD
     +_prop_1%d
        OpenAD_prop_1%d = 0.0d0
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_176 = integer_tape(integer_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_177 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_178 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_179 = double_tape(double_tape_pointer)
        double_tape_pointer = double_tape_pointer-1
        OpenAD_Symbol_180 = double_tape(double_tape_pointer)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_181 = integer_tape(integer_tape_pointer)
        X(9)%d = X(9)%d+F(INT(OpenAD_Symbol_181))%d*(OpenAD_Symbol_177)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_182 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_176))%d = X(INT(OpenAD_Symbol_176))%d+F(INT(
     +OpenAD_Symbol_182))%d*(OpenAD_Symbol_178)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_183 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_176))%d = X(INT(OpenAD_Symbol_176))%d+F(INT(
     +OpenAD_Symbol_183))%d*(OpenAD_Symbol_179)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_184 = integer_tape(integer_tape_pointer)
        X(8)%d = X(8)%d+F(INT(OpenAD_Symbol_184))%d*(OpenAD_Symbol_180)
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_185 = integer_tape(integer_tape_pointer)
        OpenAD_prop_0%d = OpenAD_prop_0%d+F(INT(OpenAD_Symbol_185))%d
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_186 = integer_tape(integer_tape_pointer)
        X(INT(OpenAD_Symbol_176))%d = X(INT(OpenAD_Symbol_176))%d+F(INT(
     +OpenAD_Symbol_186))%d
        F(INT(OpenAD_Symbol_186))%d = 0.0d0
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_187 = integer_tape(integer_tape_pointer)
        F(INT(OpenAD_Symbol_187))%d = F(INT(OpenAD_Symbol_187))%d+OpenAD
     +_prop_0%d
        OpenAD_prop_0%d = 0.0d0
        OpenAD_Symbol_136 = INT(OpenAD_Symbol_136)+1
      END DO
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_153 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_154 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_155 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_156 = double_tape(double_tape_pointer)
      X(9)%d = X(9)%d+F(2)%d*(OpenAD_Symbol_153)
      X(1)%d = X(1)%d+F(2)%d*(OpenAD_Symbol_154)
      X(1)%d = X(1)%d+F(2)%d*(OpenAD_Symbol_155)
      X(8)%d = X(8)%d+F(2)%d*(OpenAD_Symbol_156)
      X(1)%d = X(1)%d+F(2)%d
      F(2)%d = 0.0d0
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_157 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_158 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_159 = double_tape(double_tape_pointer)
      double_tape_pointer = double_tape_pointer-1
      OpenAD_Symbol_160 = double_tape(double_tape_pointer)
      X(9)%d = X(9)%d+F(1)%d*(OpenAD_Symbol_157)
      X(1)%d = X(1)%d+F(1)%d*(OpenAD_Symbol_158)
      X(1)%d = X(1)%d+F(1)%d*(OpenAD_Symbol_159)
      X(8)%d = X(8)%d+F(1)%d*(OpenAD_Symbol_160)
      X(1)%d = X(1)%d+F(1)%d*(-2.0D00)
      F(1)%d = 0.0d0
          end if
        end subroutine head
