
!$OPENAD XXX File_start [OAD_intrinsics.f90]
MODULE oad_intrinsics
use w2f__types
use OAD_active
IMPLICIT NONE
SAVE
!
!     **** Statements ****
!
END MODULE

C$OPENAD XXX File_start [all_globals_mod.f]
      MODULE all_globals_mod
      use w2f__types
      use OAD_active
      IMPLICIT NONE
      SAVE
C
C     **** Statements ****
C
      END MODULE
C#########################################################
C This file is part of OpenAD released under the LGPL.   #
C The full COPYRIGHT notice can be found in the top      #
C level directory of the OpenAD distribution             #
C#########################################################
C
C$OPENAD XXX File_start [head.f]
      SUBROUTINE find_bulkmod(LOCPRES, TFLD, SFLD, BULKMOD)
          use OAD_tape
          use OAD_rev

C original arguments get inserted before version
C         ! and declared here together with all local variables
C         ! generated by xaifBooster

      use w2f__types
      use OAD_active
      use oad_intrinsics
      use oad_intrinsics
      use oad_intrinsics
      IMPLICIT NONE
C
C     **** Global Variables & Derived Type Definitions ****
C
      INTEGER(w2f__i8) OpenAD_Symbol_112
      INTEGER(w2f__i8) OpenAD_Symbol_113
      INTEGER(w2f__i8) OpenAD_Symbol_114
      INTEGER(w2f__i8) OpenAD_Symbol_115
      INTEGER(w2f__i8) OpenAD_Symbol_116
      INTEGER(w2f__i8) OpenAD_Symbol_117
      INTEGER(w2f__i8) OpenAD_Symbol_118
      INTEGER(w2f__i8) OpenAD_Symbol_119
      INTEGER(w2f__i8) OpenAD_Symbol_120
      INTEGER(w2f__i8) OpenAD_Symbol_121
      INTEGER(w2f__i8) OpenAD_Symbol_122
      INTEGER(w2f__i8) OpenAD_Symbol_123
      INTEGER(w2f__i8) OpenAD_Symbol_124
      INTEGER(w2f__i8) OpenAD_Symbol_125
      INTEGER(w2f__i8) OpenAD_Symbol_126
      INTEGER(w2f__i8) OpenAD_Symbol_127
      INTEGER(w2f__i8) OpenAD_Symbol_128
      INTEGER(w2f__i8) OpenAD_Symbol_129
C
C     **** Parameters and Result ****
C
      type(active) :: LOCPRES(1:2,1:2)
      type(active) :: TFLD(1:2,1:2,1:2,1:2,1:2)
      type(active) :: SFLD(1:2,1:2,1:2,1:2,1:2)
      type(active) :: BULKMOD(1:2,1:2)
C
C     **** Local Variables and Functions ****
C
      INTEGER(w2f__i4) BI
      INTEGER(w2f__i4) BJ
      type(active) :: BMFRESH
      type(active) :: BMPRES
      type(active) :: BMSALT
      REAL(w2f__8) EOSJMDCKFW(1 : 5)
      REAL(w2f__8) EOSJMDCKP(1 : 14)
      REAL(w2f__8) EOSJMDCKSW(1 : 7)
      INTEGER(w2f__i4) I
      INTEGER(w2f__i4) J
      INTEGER(w2f__i4) K
      type(active) :: P
      type(active) :: P2
      type(active) :: S
      type(active) :: S3O2
      REAL(w2f__8) SITOBAR
      type(active) :: T
      type(active) :: T2
      type(active) :: T3
      type(active) :: T4
      REAL(w2f__8) OpenAD_Symbol_0
      REAL(w2f__8) OpenAD_Symbol_1
      REAL(w2f__8) OpenAD_Symbol_10
      REAL(w2f__8) OpenAD_Symbol_100
      REAL(w2f__8) OpenAD_Symbol_101
      REAL(w2f__8) OpenAD_Symbol_102
      REAL(w2f__8) OpenAD_Symbol_103
      REAL(w2f__8) OpenAD_Symbol_104
      REAL(w2f__8) OpenAD_Symbol_105
      REAL(w2f__8) OpenAD_Symbol_106
      REAL(w2f__8) OpenAD_Symbol_107
      REAL(w2f__8) OpenAD_Symbol_108
      REAL(w2f__8) OpenAD_Symbol_109
      REAL(w2f__8) OpenAD_Symbol_110
      REAL(w2f__8) OpenAD_Symbol_111
      REAL(w2f__8) OpenAD_Symbol_12
      REAL(w2f__8) OpenAD_Symbol_13
      REAL(w2f__8) OpenAD_Symbol_16
      INTEGER(w2f__i8) OpenAD_Symbol_173
      INTEGER(w2f__i8) OpenAD_Symbol_174
      INTEGER(w2f__i8) OpenAD_Symbol_175
      INTEGER(w2f__i8) OpenAD_Symbol_176
      INTEGER(w2f__i8) OpenAD_Symbol_177
      REAL(w2f__8) OpenAD_Symbol_178
      REAL(w2f__8) OpenAD_Symbol_179
      REAL(w2f__8) OpenAD_Symbol_18
      REAL(w2f__8) OpenAD_Symbol_180
      REAL(w2f__8) OpenAD_Symbol_181
      REAL(w2f__8) OpenAD_Symbol_182
      INTEGER(w2f__i8) OpenAD_Symbol_183
      INTEGER(w2f__i8) OpenAD_Symbol_184
      REAL(w2f__8) OpenAD_Symbol_185
      REAL(w2f__8) OpenAD_Symbol_186
      REAL(w2f__8) OpenAD_Symbol_187
      REAL(w2f__8) OpenAD_Symbol_188
      REAL(w2f__8) OpenAD_Symbol_189
      REAL(w2f__8) OpenAD_Symbol_190
      REAL(w2f__8) OpenAD_Symbol_191
      REAL(w2f__8) OpenAD_Symbol_192
      REAL(w2f__8) OpenAD_Symbol_193
      REAL(w2f__8) OpenAD_Symbol_194
      REAL(w2f__8) OpenAD_Symbol_195
      REAL(w2f__8) OpenAD_Symbol_196
      REAL(w2f__8) OpenAD_Symbol_197
      REAL(w2f__8) OpenAD_Symbol_198
      REAL(w2f__8) OpenAD_Symbol_199
      REAL(w2f__8) OpenAD_Symbol_2
      REAL(w2f__8) OpenAD_Symbol_20
      REAL(w2f__8) OpenAD_Symbol_200
      REAL(w2f__8) OpenAD_Symbol_201
      REAL(w2f__8) OpenAD_Symbol_202
      REAL(w2f__8) OpenAD_Symbol_203
      REAL(w2f__8) OpenAD_Symbol_204
      REAL(w2f__8) OpenAD_Symbol_205
      REAL(w2f__8) OpenAD_Symbol_206
      REAL(w2f__8) OpenAD_Symbol_207
      REAL(w2f__8) OpenAD_Symbol_208
      REAL(w2f__8) OpenAD_Symbol_22
      REAL(w2f__8) OpenAD_Symbol_23
      REAL(w2f__8) OpenAD_Symbol_24
      REAL(w2f__8) OpenAD_Symbol_25
      REAL(w2f__8) OpenAD_Symbol_28
      REAL(w2f__8) OpenAD_Symbol_3
      REAL(w2f__8) OpenAD_Symbol_30
      REAL(w2f__8) OpenAD_Symbol_32
      REAL(w2f__8) OpenAD_Symbol_33
      REAL(w2f__8) OpenAD_Symbol_34
      REAL(w2f__8) OpenAD_Symbol_35
      REAL(w2f__8) OpenAD_Symbol_38
      REAL(w2f__8) OpenAD_Symbol_4
      REAL(w2f__8) OpenAD_Symbol_40
      REAL(w2f__8) OpenAD_Symbol_41
      REAL(w2f__8) OpenAD_Symbol_42
      REAL(w2f__8) OpenAD_Symbol_43
      REAL(w2f__8) OpenAD_Symbol_46
      REAL(w2f__8) OpenAD_Symbol_48
      REAL(w2f__8) OpenAD_Symbol_5
      REAL(w2f__8) OpenAD_Symbol_50
      REAL(w2f__8) OpenAD_Symbol_51
      REAL(w2f__8) OpenAD_Symbol_52
      REAL(w2f__8) OpenAD_Symbol_53
      REAL(w2f__8) OpenAD_Symbol_54
      REAL(w2f__8) OpenAD_Symbol_55
      REAL(w2f__8) OpenAD_Symbol_56
      REAL(w2f__8) OpenAD_Symbol_59
      REAL(w2f__8) OpenAD_Symbol_6
      REAL(w2f__8) OpenAD_Symbol_61
      REAL(w2f__8) OpenAD_Symbol_62
      REAL(w2f__8) OpenAD_Symbol_64
      REAL(w2f__8) OpenAD_Symbol_65
      REAL(w2f__8) OpenAD_Symbol_66
      REAL(w2f__8) OpenAD_Symbol_67
      REAL(w2f__8) OpenAD_Symbol_68
      REAL(w2f__8) OpenAD_Symbol_69
      REAL(w2f__8) OpenAD_Symbol_7
      REAL(w2f__8) OpenAD_Symbol_72
      REAL(w2f__8) OpenAD_Symbol_74
      REAL(w2f__8) OpenAD_Symbol_75
      REAL(w2f__8) OpenAD_Symbol_76
      REAL(w2f__8) OpenAD_Symbol_77
      REAL(w2f__8) OpenAD_Symbol_78
      REAL(w2f__8) OpenAD_Symbol_79
      REAL(w2f__8) OpenAD_Symbol_8
      REAL(w2f__8) OpenAD_Symbol_80
      REAL(w2f__8) OpenAD_Symbol_83
      REAL(w2f__8) OpenAD_Symbol_85
      REAL(w2f__8) OpenAD_Symbol_89
      REAL(w2f__8) OpenAD_Symbol_9
      REAL(w2f__8) OpenAD_Symbol_90
      REAL(w2f__8) OpenAD_Symbol_91
      REAL(w2f__8) OpenAD_Symbol_92
      REAL(w2f__8) OpenAD_Symbol_93
      REAL(w2f__8) OpenAD_Symbol_94
      REAL(w2f__8) OpenAD_Symbol_95
      REAL(w2f__8) OpenAD_Symbol_96
      REAL(w2f__8) OpenAD_Symbol_97
      REAL(w2f__8) OpenAD_Symbol_98
      REAL(w2f__8) OpenAD_Symbol_99


          integer iaddr
          external iaddr
C
C     **** Statements ****
C

         if (our_rev_mode%plain) then
C original function
C$OPENAD XXX Template ad_template.f
      EOSJMDCKFW(1) = 1.9659330078E+04
      EOSJMDCKFW(2) = 1.4443040466E+02
      EOSJMDCKFW(3) = (-1.7061029673)
      EOSJMDCKFW(4) = 9.64870397E-03
      EOSJMDCKFW(5) = (-4.1902530938E-05)
      EOSJMDCKSW(1) = 5.2848548889E+01
      EOSJMDCKSW(2) = (-3.1010890007E-01)
      EOSJMDCKSW(3) = 6.2832632102E-03
      EOSJMDCKSW(4) = (-5.0841881603E-05)
      EOSJMDCKSW(5) = 3.8866400719E-01
      EOSJMDCKSW(6) = 9.085830301E-03
      EOSJMDCKSW(7) = (-4.6199240023E-04)
      EOSJMDCKP(1) = 3.1865189075
      EOSJMDCKP(2) = 2.2122759372E-02
      EOSJMDCKP(3) = (-2.9846420512E-04)
      EOSJMDCKP(4) = 1.9564149625E-06
      EOSJMDCKP(5) = 6.7043881863E-03
      EOSJMDCKP(6) = (-1.8473180535E-04)
      EOSJMDCKP(7) = 2.0593310524E-07
      EOSJMDCKP(8) = 1.480265928E-04
      EOSJMDCKP(9) = 2.1028979972E-04
      EOSJMDCKP(10) = (-1.2020160284E-05)
      EOSJMDCKP(11) = 1.3946799982E-07
      EOSJMDCKP(12) = (-2.0402369501E-06)
      EOSJMDCKP(13) = 6.128772867E-08
      EOSJMDCKP(14) = 6.2073229889E-10
      K = 1
      BI = 1
      BJ = 1
      SITOBAR = 1.0D00
      DO J = 1, 2, 1
        DO I = 1, 2, 1
          T%v = TFLD(I,J,K,BI,BJ)%v
          T2%v = (T%v*T%v)
          T3%v = (T%v*T2%v)
          T4%v = (T%v*T3%v)
          S%v = SFLD(I,J,K,BI,BJ)%v
          IF (S%v.GT.0.0D00) THEN
            S3O2%v = (S%v*SQRT(S%v))
          ELSE
            S%v = 0.0D00
            S3O2%v = 0.0D00
          ENDIF
          P%v = (LOCPRES(I,J)%v*SITOBAR)
          P2%v = (P%v*P%v)
          BMFRESH%v = (EOSJMDCKFW(1)+EOSJMDCKFW(2)*T%v+EOSJMDCKFW(3)*T2%
     +v+EOSJMDCKFW(4)*T3%v+EOSJMDCKFW(5)*T4%v)
          BMSALT%v = (S%v*(EOSJMDCKSW(1)+EOSJMDCKSW(2)*T%v+EOSJMDCKSW(3)
     +*T2%v+EOSJMDCKSW(4)*T3%v)+S3O2%v*(EOSJMDCKSW(5)+EOSJMDCKSW(6)*T%v+
     +EOSJMDCKSW(7)*T2%v))
          BMPRES%v = (P%v*(EOSJMDCKP(1)+EOSJMDCKP(2)*T%v+EOSJMDCKP(3)*T2
     +%v+EOSJMDCKP(4)*T3%v)+P%v*S%v*(EOSJMDCKP(5)+EOSJMDCKP(6)*T%v+EOSJM
     +DCKP(7)*T2%v)+EOSJMDCKP(8)*P%v*S3O2%v+P2%v*(EOSJMDCKP(9)+EOSJMDCKP
     +(10)*T%v+EOSJMDCKP(11)*T2%v)+P2%v*S%v*(EOSJMDCKP(12)+EOSJMDCKP(13)
     +*T%v+EOSJMDCKP(14)*T2%v))
          BULKMOD(INT(I),INT(J))%v = (BMPRES%v+BMFRESH%v+BMSALT%v)
        END DO
      END DO
          end if
          if (our_rev_mode%tape) then
C taping
C$OPENAD XXX Template ad_template.f
      EOSJMDCKFW(1) = 1.9659330078E+04
      EOSJMDCKFW(2) = 1.4443040466E+02
      EOSJMDCKFW(3) = (-1.7061029673)
      EOSJMDCKFW(4) = 9.64870397E-03
      EOSJMDCKFW(5) = (-4.1902530938E-05)
      EOSJMDCKSW(1) = 5.2848548889E+01
      EOSJMDCKSW(2) = (-3.1010890007E-01)
      EOSJMDCKSW(3) = 6.2832632102E-03
      EOSJMDCKSW(4) = (-5.0841881603E-05)
      EOSJMDCKSW(5) = 3.8866400719E-01
      EOSJMDCKSW(6) = 9.085830301E-03
      EOSJMDCKSW(7) = (-4.6199240023E-04)
      EOSJMDCKP(1) = 3.1865189075
      EOSJMDCKP(2) = 2.2122759372E-02
      EOSJMDCKP(3) = (-2.9846420512E-04)
      EOSJMDCKP(4) = 1.9564149625E-06
      EOSJMDCKP(5) = 6.7043881863E-03
      EOSJMDCKP(6) = (-1.8473180535E-04)
      EOSJMDCKP(7) = 2.0593310524E-07
      EOSJMDCKP(8) = 1.480265928E-04
      EOSJMDCKP(9) = 2.1028979972E-04
      EOSJMDCKP(10) = (-1.2020160284E-05)
      EOSJMDCKP(11) = 1.3946799982E-07
      EOSJMDCKP(12) = (-2.0402369501E-06)
      EOSJMDCKP(13) = 6.128772867E-08
      EOSJMDCKP(14) = 6.2073229889E-10
      K = 1
      BI = 1
      BJ = 1
      SITOBAR = 1.0D00
      OpenAD_Symbol_117 = 0_w2f__i8
      DO J = 1,2,1
        OpenAD_Symbol_118 = 0_w2f__i8
        DO I = 1,2,1
          T%v = TFLD(I,J,K,BI,BJ)%v
          T2%v = (T%v*T%v)
          OpenAD_Symbol_0 = T%v
          OpenAD_Symbol_1 = T%v
          T3%v = (T%v*T2%v)
          OpenAD_Symbol_2 = T2%v
          OpenAD_Symbol_3 = T%v
          T4%v = (T%v*T3%v)
          OpenAD_Symbol_4 = T3%v
          OpenAD_Symbol_5 = T%v
          S%v = SFLD(I,J,K,BI,BJ)%v
          OpenAD_Symbol_89 = (OpenAD_Symbol_0+OpenAD_Symbol_1)
          OpenAD_Symbol_90 = (OpenAD_Symbol_2+OpenAD_Symbol_89*OpenAD_Sy
     +mbol_3)
          OpenAD_Symbol_91 = (OpenAD_Symbol_4+OpenAD_Symbol_90*OpenAD_Sy
     +mbol_5)
          double_tape(double_tape_pointer) = OpenAD_Symbol_89
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_90
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_91
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = J
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = K
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = BI
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = BJ
          integer_tape_pointer = integer_tape_pointer+1
          IF (S%v.GT.0.0D00) THEN
            OpenAD_Symbol_6 = SQRT(S%v)
            S3O2%v = (S%v*OpenAD_Symbol_6)
            OpenAD_Symbol_7 = OpenAD_Symbol_6
            OpenAD_Symbol_9 = (5.0D-01/OpenAD_Symbol_6)
            OpenAD_Symbol_8 = S%v
            OpenAD_Symbol_92 = (OpenAD_Symbol_9*OpenAD_Symbol_8)
            double_tape(double_tape_pointer) = OpenAD_Symbol_7
            double_tape_pointer = double_tape_pointer+1
            double_tape(double_tape_pointer) = OpenAD_Symbol_92
            double_tape_pointer = double_tape_pointer+1
            OpenAD_Symbol_119 = 1_w2f__i8
            integer_tape(integer_tape_pointer) = OpenAD_Symbol_119
            integer_tape_pointer = integer_tape_pointer+1
          ELSE
            S%v = 0.0D00
            S3O2%v = 0.0D00
            OpenAD_Symbol_120 = 0_w2f__i8
            integer_tape(integer_tape_pointer) = OpenAD_Symbol_120
            integer_tape_pointer = integer_tape_pointer+1
          ENDIF
          P%v = (LOCPRES(I,J)%v*SITOBAR)
          OpenAD_Symbol_10 = SITOBAR
          P2%v = (P%v*P%v)
          OpenAD_Symbol_12 = P%v
          OpenAD_Symbol_13 = P%v
          BMFRESH%v = (EOSJMDCKFW(1)+EOSJMDCKFW(2)*T%v+EOSJMDCKFW(3)*T2%
     +v+EOSJMDCKFW(4)*T3%v+EOSJMDCKFW(5)*T4%v)
          OpenAD_Symbol_16 = EOSJMDCKFW(2)
          OpenAD_Symbol_18 = EOSJMDCKFW(3)
          OpenAD_Symbol_20 = EOSJMDCKFW(4)
          OpenAD_Symbol_22 = EOSJMDCKFW(5)
          OpenAD_Symbol_23 = (EOSJMDCKSW(1)+EOSJMDCKSW(2)*T%v+EOSJMDCKSW
     +(3)*T2%v+EOSJMDCKSW(4)*T3%v)
          OpenAD_Symbol_33 = (EOSJMDCKSW(5)+EOSJMDCKSW(6)*T%v+EOSJMDCKSW
     +(7)*T2%v)
          BMSALT%v = (S%v*OpenAD_Symbol_23+S3O2%v*OpenAD_Symbol_33)
          OpenAD_Symbol_24 = OpenAD_Symbol_23
          OpenAD_Symbol_28 = EOSJMDCKSW(2)
          OpenAD_Symbol_30 = EOSJMDCKSW(3)
          OpenAD_Symbol_32 = EOSJMDCKSW(4)
          OpenAD_Symbol_25 = S%v
          OpenAD_Symbol_34 = OpenAD_Symbol_33
          OpenAD_Symbol_38 = EOSJMDCKSW(6)
          OpenAD_Symbol_40 = EOSJMDCKSW(7)
          OpenAD_Symbol_35 = S3O2%v
          OpenAD_Symbol_41 = (EOSJMDCKP(1)+EOSJMDCKP(2)*T%v+EOSJMDCKP(3)
     +*T2%v+EOSJMDCKP(4)*T3%v)
          OpenAD_Symbol_51 = (P%v*S%v)
          OpenAD_Symbol_52 = (EOSJMDCKP(5)+EOSJMDCKP(6)*T%v+EOSJMDCKP(7)
     +*T2%v)
          OpenAD_Symbol_62 = (P%v*S3O2%v)
          OpenAD_Symbol_67 = (EOSJMDCKP(9)+EOSJMDCKP(10)*T%v+EOSJMDCKP(1
     +1)*T2%v)
          OpenAD_Symbol_75 = (P2%v*S%v)
          OpenAD_Symbol_76 = (EOSJMDCKP(12)+EOSJMDCKP(13)*T%v+EOSJMDCKP(
     +14)*T2%v)
          BMPRES%v = (P%v*OpenAD_Symbol_41+OpenAD_Symbol_51*OpenAD_Symbo
     +l_52+EOSJMDCKP(8)*OpenAD_Symbol_62+P2%v*OpenAD_Symbol_67+OpenAD_Sy
     +mbol_75*OpenAD_Symbol_76)
          OpenAD_Symbol_42 = OpenAD_Symbol_41
          OpenAD_Symbol_46 = EOSJMDCKP(2)
          OpenAD_Symbol_48 = EOSJMDCKP(3)
          OpenAD_Symbol_50 = EOSJMDCKP(4)
          OpenAD_Symbol_43 = P%v
          OpenAD_Symbol_55 = S%v
          OpenAD_Symbol_56 = P%v
          OpenAD_Symbol_53 = OpenAD_Symbol_52
          OpenAD_Symbol_59 = EOSJMDCKP(6)
          OpenAD_Symbol_61 = EOSJMDCKP(7)
          OpenAD_Symbol_54 = OpenAD_Symbol_51
          OpenAD_Symbol_65 = S3O2%v
          OpenAD_Symbol_66 = P%v
          OpenAD_Symbol_64 = EOSJMDCKP(8)
          OpenAD_Symbol_68 = OpenAD_Symbol_67
          OpenAD_Symbol_72 = EOSJMDCKP(10)
          OpenAD_Symbol_74 = EOSJMDCKP(11)
          OpenAD_Symbol_69 = P2%v
          OpenAD_Symbol_79 = S%v
          OpenAD_Symbol_80 = P2%v
          OpenAD_Symbol_77 = OpenAD_Symbol_76
          OpenAD_Symbol_83 = EOSJMDCKP(13)
          OpenAD_Symbol_85 = EOSJMDCKP(14)
          OpenAD_Symbol_78 = OpenAD_Symbol_75
          BULKMOD(INT(I),INT(J))%v = (BMPRES%v+BMFRESH%v+BMSALT%v)
          OpenAD_Symbol_93 = (OpenAD_Symbol_80*OpenAD_Symbol_77)
          OpenAD_Symbol_94 = (OpenAD_Symbol_56*OpenAD_Symbol_53)
          OpenAD_Symbol_95 = (OpenAD_Symbol_50*OpenAD_Symbol_43)
          OpenAD_Symbol_96 = (OpenAD_Symbol_32*OpenAD_Symbol_25)
          OpenAD_Symbol_97 = (OpenAD_Symbol_85*OpenAD_Symbol_78)
          OpenAD_Symbol_98 = (OpenAD_Symbol_74*OpenAD_Symbol_69)
          OpenAD_Symbol_99 = (OpenAD_Symbol_61*OpenAD_Symbol_54)
          OpenAD_Symbol_100 = (OpenAD_Symbol_48*OpenAD_Symbol_43)
          OpenAD_Symbol_101 = (OpenAD_Symbol_40*OpenAD_Symbol_35)
          OpenAD_Symbol_102 = (OpenAD_Symbol_30*OpenAD_Symbol_25)
          OpenAD_Symbol_103 = (OpenAD_Symbol_83*OpenAD_Symbol_78)
          OpenAD_Symbol_104 = (OpenAD_Symbol_72*OpenAD_Symbol_69)
          OpenAD_Symbol_105 = (OpenAD_Symbol_66*OpenAD_Symbol_64)
          OpenAD_Symbol_106 = (OpenAD_Symbol_59*OpenAD_Symbol_54)
          OpenAD_Symbol_107 = (OpenAD_Symbol_46*OpenAD_Symbol_43)
          OpenAD_Symbol_108 = (OpenAD_Symbol_38*OpenAD_Symbol_35)
          OpenAD_Symbol_109 = (OpenAD_Symbol_28*OpenAD_Symbol_25)
          OpenAD_Symbol_110 = (OpenAD_Symbol_12+OpenAD_Symbol_13)
          OpenAD_Symbol_111 = (OpenAD_Symbol_10*OpenAD_Symbol_42+OpenAD_
     +Symbol_10*OpenAD_Symbol_110*OpenAD_Symbol_79*OpenAD_Symbol_77+Open
     +AD_Symbol_10*OpenAD_Symbol_110*OpenAD_Symbol_68+OpenAD_Symbol_10*O
     +penAD_Symbol_55*OpenAD_Symbol_53+OpenAD_Symbol_10*OpenAD_Symbol_65
     +*OpenAD_Symbol_64)
          double_tape(double_tape_pointer) = OpenAD_Symbol_111
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_24
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_93
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_94
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_95
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_34
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_96
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_97
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_98
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_99
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_100
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_101
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_102
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_103
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_104
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_105
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_106
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_107
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_108
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_109
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_18
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_20
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_22
          double_tape_pointer = double_tape_pointer+1
          double_tape(double_tape_pointer) = OpenAD_Symbol_16
          double_tape_pointer = double_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = J
          integer_tape_pointer = integer_tape_pointer+1
          OpenAD_Symbol_118 = (INT(OpenAD_Symbol_118)+INT(1_w2f__i8))
        END DO
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_118
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_117 = (INT(OpenAD_Symbol_117)+INT(1_w2f__i8))
      END DO
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_117
      integer_tape_pointer = integer_tape_pointer+1
          end if
          if (our_rev_mode%adjoint) then
C adjoint
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_112 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_113 = 1
      do while (INT(OpenAD_Symbol_113).LE.INT(OpenAD_Symbol_112))
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_114 = integer_tape(integer_tape_pointer)
        OpenAD_Symbol_115 = 1
        do while (INT(OpenAD_Symbol_115).LE.INT(OpenAD_Symbol_114))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_183 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_184 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_185 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_186 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_187 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_188 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_189 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_190 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_191 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_192 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_193 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_194 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_195 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_196 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_197 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_198 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_199 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_200 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_201 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_202 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_203 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_204 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_205 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_206 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_207 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_208 = double_tape(double_tape_pointer)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_185)
          T4%d = T4%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_186)
          T3%d = T3%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_187)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_188)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_189)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_190)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_191)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_192)
          S3O2%d = S3O2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symb
     +ol_183))%d*(OpenAD_Symbol_193)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_194)
          T%d = T%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_195)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_196)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_197)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_198)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_199)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_200)
          T2%d = T2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_201)
          T3%d = T3%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_202)
          S3O2%d = S3O2%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symb
     +ol_183))%d*(OpenAD_Symbol_203)
          T3%d = T3%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_1
     +83))%d*(OpenAD_Symbol_204)
          S%d = S%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_205)
          S%d = S%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_206)
          S%d = S%d+BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183
     +))%d*(OpenAD_Symbol_207)
          LOCPRES(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183))%d = LOC
     +PRES(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183))%d+BULKMOD(INT(
     +OpenAD_Symbol_184),INT(OpenAD_Symbol_183))%d*(OpenAD_Symbol_208)
          BULKMOD(INT(OpenAD_Symbol_184),INT(OpenAD_Symbol_183))%d = 0.0
     +d0
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_116 = integer_tape(integer_tape_pointer)
          IF (OpenAD_Symbol_116.ne.0) THEN
            double_tape_pointer = double_tape_pointer-1
            OpenAD_Symbol_181 = double_tape(double_tape_pointer)
            double_tape_pointer = double_tape_pointer-1
            OpenAD_Symbol_182 = double_tape(double_tape_pointer)
            S%d = S%d+S3O2%d*(OpenAD_Symbol_181)
            S%d = S%d+S3O2%d*(OpenAD_Symbol_182)
            S3O2%d = 0.0d0
          ELSE
            S3O2%d = 0.0d0
            S%d = 0.0d0
          ENDIF
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_173 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_174 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_175 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_176 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_177 = integer_tape(integer_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_178 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_179 = double_tape(double_tape_pointer)
          double_tape_pointer = double_tape_pointer-1
          OpenAD_Symbol_180 = double_tape(double_tape_pointer)
          SFLD(INT(OpenAD_Symbol_177),INT(OpenAD_Symbol_176),INT(OpenAD_
     +Symbol_175),INT(OpenAD_Symbol_174),INT(OpenAD_Symbol_173))%d = SFL
     +D(INT(OpenAD_Symbol_177),INT(OpenAD_Symbol_176),INT(OpenAD_Symbol_
     +175),INT(OpenAD_Symbol_174),INT(OpenAD_Symbol_173))%d+S%d
          S%d = 0.0d0
          T%d = T%d+T4%d*(OpenAD_Symbol_178)
          T4%d = 0.0d0
          T%d = T%d+T3%d*(OpenAD_Symbol_179)
          T3%d = 0.0d0
          T%d = T%d+T2%d*(OpenAD_Symbol_180)
          T2%d = 0.0d0
          TFLD(INT(OpenAD_Symbol_177),INT(OpenAD_Symbol_176),INT(OpenAD_
     +Symbol_175),INT(OpenAD_Symbol_174),INT(OpenAD_Symbol_173))%d = TFL
     +D(INT(OpenAD_Symbol_177),INT(OpenAD_Symbol_176),INT(OpenAD_Symbol_
     +175),INT(OpenAD_Symbol_174),INT(OpenAD_Symbol_173))%d+T%d
          T%d = 0.0d0
          OpenAD_Symbol_115 = INT(OpenAD_Symbol_115)+1
        END DO
        OpenAD_Symbol_113 = INT(OpenAD_Symbol_113)+1
      END DO
          end if
        end subroutine find_bulkmod
C#########################################################
C This file is part of OpenAD released under the LGPL.   #
C The full COPYRIGHT notice can be found in the top      #
C level directory of the OpenAD distribution             #
C#########################################################

      SUBROUTINE head(X, Y)
          use OAD_tape
          use OAD_rev

C original arguments get inserted before version
C         ! and declared here together with all local variables
C         ! generated by xaifBooster

      use w2f__types
      use OAD_active
      use oad_intrinsics
      use oad_intrinsics
      use oad_intrinsics
      IMPLICIT NONE
C
C     **** Global Variables & Derived Type Definitions ****
C
      INTEGER(w2f__i8) OpenAD_Symbol_130
      INTEGER(w2f__i8) OpenAD_Symbol_131
      INTEGER(w2f__i8) OpenAD_Symbol_132
      INTEGER(w2f__i8) OpenAD_Symbol_133
      INTEGER(w2f__i8) OpenAD_Symbol_134
      INTEGER(w2f__i8) OpenAD_Symbol_135
      INTEGER(w2f__i8) OpenAD_Symbol_136
      INTEGER(w2f__i8) OpenAD_Symbol_137
      INTEGER(w2f__i8) OpenAD_Symbol_138
      INTEGER(w2f__i8) OpenAD_Symbol_139
      INTEGER(w2f__i8) OpenAD_Symbol_140
      INTEGER(w2f__i8) OpenAD_Symbol_141
      INTEGER(w2f__i8) OpenAD_Symbol_142
      INTEGER(w2f__i8) OpenAD_Symbol_143
      INTEGER(w2f__i8) OpenAD_Symbol_144
      INTEGER(w2f__i8) OpenAD_Symbol_145
      INTEGER(w2f__i8) OpenAD_Symbol_146
      INTEGER(w2f__i8) OpenAD_Symbol_147
      INTEGER(w2f__i8) OpenAD_Symbol_148
      INTEGER(w2f__i8) OpenAD_Symbol_149
      INTEGER(w2f__i8) OpenAD_Symbol_150
      INTEGER(w2f__i8) OpenAD_Symbol_151
      INTEGER(w2f__i8) OpenAD_Symbol_152
      INTEGER(w2f__i8) OpenAD_Symbol_153
      INTEGER(w2f__i8) OpenAD_Symbol_154
      INTEGER(w2f__i8) OpenAD_Symbol_155
      INTEGER(w2f__i8) OpenAD_Symbol_156
      INTEGER(w2f__i8) OpenAD_Symbol_157
      INTEGER(w2f__i8) OpenAD_Symbol_158
      INTEGER(w2f__i8) OpenAD_Symbol_159
      INTEGER(w2f__i8) OpenAD_Symbol_160
      INTEGER(w2f__i8) OpenAD_Symbol_161
      INTEGER(w2f__i8) OpenAD_Symbol_162
      INTEGER(w2f__i8) OpenAD_Symbol_163
      INTEGER(w2f__i8) OpenAD_Symbol_164
      INTEGER(w2f__i8) OpenAD_Symbol_165
      INTEGER(w2f__i8) OpenAD_Symbol_166
      INTEGER(w2f__i8) OpenAD_Symbol_167
      INTEGER(w2f__i8) OpenAD_Symbol_168
      INTEGER(w2f__i8) OpenAD_Symbol_169
      INTEGER(w2f__i8) OpenAD_Symbol_170
      INTEGER(w2f__i8) OpenAD_Symbol_171
C
C     **** Parameters and Result ****
C
      type(active) :: X(1:32)
      type(active) :: Y(1:4)
C
C     **** Local Variables and Functions ****
C
      type(active) :: BULKMOD(1:2,1:2)
      EXTERNAL find_bulkmod
      INTEGER(w2f__i4) I
      INTEGER(w2f__i4) J
      INTEGER(w2f__i4) K
      INTEGER(w2f__i4) L
      type(active) :: LOCPRES(1:2,1:2)
      INTEGER(w2f__i4) M
      type(active) :: SFLD(1:2,1:2,1:2,1:2,1:2)
      type(active) :: TFLD(1:2,1:2,1:2,1:2,1:2)
      INTEGER(w2f__i4) XCOUNT
      INTEGER(w2f__i8) OpenAD_Symbol_172
      INTEGER(w2f__i8) OpenAD_Symbol_209
      INTEGER(w2f__i8) OpenAD_Symbol_210
      INTEGER(w2f__i8) OpenAD_Symbol_211
      INTEGER(w2f__i8) OpenAD_Symbol_212
      INTEGER(w2f__i8) OpenAD_Symbol_213
      INTEGER(w2f__i8) OpenAD_Symbol_214
      INTEGER(w2f__i8) OpenAD_Symbol_215
      INTEGER(w2f__i8) OpenAD_Symbol_216
      INTEGER(w2f__i8) OpenAD_Symbol_217
      INTEGER(w2f__i8) OpenAD_Symbol_218
      INTEGER(w2f__i8) OpenAD_Symbol_219
      INTEGER(w2f__i8) OpenAD_Symbol_220


          integer iaddr
          external iaddr
C
C     **** Top Level Pragmas ****
C
C$OPENAD INDEPENDENT(X)
C$OPENAD DEPENDENT(Y)
C
C     **** Statements ****
C

         if (our_rev_mode%plain) then
C original function
C$OPENAD XXX Template ad_template.f
      XCOUNT = 1
      DO I = 1, 2, 1
        DO J = 1, 2, 1
          LOCPRES(INT(I),INT(J))%v = (X(XCOUNT)%v*2.0D00)
          DO K = 1,2,1
            DO L = 1,2,1
              DO M = 1,2,1
                TFLD(INT(I),INT(J),INT(K),INT(L),INT(M))%v = (X(XCOUNT)%
     +v*3.0D00)
                SFLD(INT(I),INT(J),INT(K),INT(L),INT(M))%v = (X(XCOUNT)%
     +v*4.0D00)
                XCOUNT = (XCOUNT+1)
              END DO
            END DO
          END DO
        END DO
      END DO
      CALL find_bulkmod(LOCPRES,TFLD,SFLD,BULKMOD)
      DO I = 1,2,1
        DO J = 1,2,1
          Y(INT(J+INT((I*2))+(-2)))%v = BULKMOD(I,J)%v
        END DO
      END DO
          end if
          if (our_rev_mode%tape) then
C taping
C$OPENAD XXX Template ad_template.f
      XCOUNT = 1
      OpenAD_Symbol_144 = 0_w2f__i8
      DO I = 1,2,1
        OpenAD_Symbol_145 = 0_w2f__i8
        DO J = 1,2,1
          LOCPRES(INT(I),INT(J))%v = (X(XCOUNT)%v*2.0D00)
          integer_tape(integer_tape_pointer) = XCOUNT
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = J
          integer_tape_pointer = integer_tape_pointer+1
          OpenAD_Symbol_146 = 0_w2f__i8
          DO K = 1,2,1
            OpenAD_Symbol_147 = 0_w2f__i8
            DO L = 1,2,1
              OpenAD_Symbol_148 = 0_w2f__i8
              DO M = 1,2,1
                TFLD(INT(I),INT(J),INT(K),INT(L),INT(M))%v = (X(XCOUNT)%
     +v*3.0D00)
                SFLD(INT(I),INT(J),INT(K),INT(L),INT(M))%v = (X(XCOUNT)%
     +v*4.0D00)
                integer_tape(integer_tape_pointer) = XCOUNT
                integer_tape_pointer = integer_tape_pointer+1
                integer_tape(integer_tape_pointer) = I
                integer_tape_pointer = integer_tape_pointer+1
                integer_tape(integer_tape_pointer) = J
                integer_tape_pointer = integer_tape_pointer+1
                integer_tape(integer_tape_pointer) = K
                integer_tape_pointer = integer_tape_pointer+1
                integer_tape(integer_tape_pointer) = L
                integer_tape_pointer = integer_tape_pointer+1
                integer_tape(integer_tape_pointer) = M
                integer_tape_pointer = integer_tape_pointer+1
                XCOUNT = (XCOUNT+1)
                OpenAD_Symbol_148 = (INT(OpenAD_Symbol_148)+INT(1_w2f__i
     +8))
              END DO
              integer_tape(integer_tape_pointer) = OpenAD_Symbol_148
              integer_tape_pointer = integer_tape_pointer+1
              OpenAD_Symbol_147 = (INT(OpenAD_Symbol_147)+INT(1_w2f__i8)
     +)
            END DO
            integer_tape(integer_tape_pointer) = OpenAD_Symbol_147
            integer_tape_pointer = integer_tape_pointer+1
            OpenAD_Symbol_146 = (INT(OpenAD_Symbol_146)+INT(1_w2f__i8))
          END DO
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_146
          integer_tape_pointer = integer_tape_pointer+1
          OpenAD_Symbol_145 = (INT(OpenAD_Symbol_145)+INT(1_w2f__i8))
        END DO
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_145
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_144 = (INT(OpenAD_Symbol_144)+INT(1_w2f__i8))
      END DO
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_144
      integer_tape_pointer = integer_tape_pointer+1
      CALL find_bulkmod(LOCPRES,TFLD,SFLD,BULKMOD)
      OpenAD_Symbol_149 = 0_w2f__i8
      DO I = 1,2,1
        OpenAD_Symbol_150 = 0_w2f__i8
        DO J = 1,2,1
          Y(INT(J+INT((I*2))+(-2)))%v = BULKMOD(I,J)%v
          OpenAD_Symbol_172 = (J+I*2+(-2))
          integer_tape(integer_tape_pointer) = OpenAD_Symbol_172
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = I
          integer_tape_pointer = integer_tape_pointer+1
          integer_tape(integer_tape_pointer) = J
          integer_tape_pointer = integer_tape_pointer+1
          OpenAD_Symbol_150 = (INT(OpenAD_Symbol_150)+INT(1_w2f__i8))
        END DO
        integer_tape(integer_tape_pointer) = OpenAD_Symbol_150
        integer_tape_pointer = integer_tape_pointer+1
        OpenAD_Symbol_149 = (INT(OpenAD_Symbol_149)+INT(1_w2f__i8))
      END DO
      integer_tape(integer_tape_pointer) = OpenAD_Symbol_149
      integer_tape_pointer = integer_tape_pointer+1
          end if
          if (our_rev_mode%adjoint) then
C adjoint
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_130 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_131 = 1
      do while (INT(OpenAD_Symbol_131).LE.INT(OpenAD_Symbol_130))
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_132 = integer_tape(integer_tape_pointer)
        OpenAD_Symbol_133 = 1
        do while (INT(OpenAD_Symbol_133).LE.INT(OpenAD_Symbol_132))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_218 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_219 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_220 = integer_tape(integer_tape_pointer)
          BULKMOD(INT(OpenAD_Symbol_219),INT(OpenAD_Symbol_218))%d = BUL
     +KMOD(INT(OpenAD_Symbol_219),INT(OpenAD_Symbol_218))%d+Y(INT(OpenAD
     +_Symbol_220))%d
          Y(INT(OpenAD_Symbol_220))%d = 0.0d0
          OpenAD_Symbol_133 = INT(OpenAD_Symbol_133)+1
        END DO
        OpenAD_Symbol_131 = INT(OpenAD_Symbol_131)+1
      END DO
      CALL find_bulkmod(LOCPRES,TFLD,SFLD,BULKMOD)
      integer_tape_pointer = integer_tape_pointer-1
      OpenAD_Symbol_134 = integer_tape(integer_tape_pointer)
      OpenAD_Symbol_135 = 1
      do while (INT(OpenAD_Symbol_135).LE.INT(OpenAD_Symbol_134))
        integer_tape_pointer = integer_tape_pointer-1
        OpenAD_Symbol_136 = integer_tape(integer_tape_pointer)
        OpenAD_Symbol_137 = 1
        do while (INT(OpenAD_Symbol_137).LE.INT(OpenAD_Symbol_136))
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_138 = integer_tape(integer_tape_pointer)
          OpenAD_Symbol_139 = 1
          do while (INT(OpenAD_Symbol_139).LE.INT(OpenAD_Symbol_138))
            integer_tape_pointer = integer_tape_pointer-1
            OpenAD_Symbol_140 = integer_tape(integer_tape_pointer)
            OpenAD_Symbol_141 = 1
            do while (INT(OpenAD_Symbol_141).LE.INT(OpenAD_Symbol_140))
              integer_tape_pointer = integer_tape_pointer-1
              OpenAD_Symbol_142 = integer_tape(integer_tape_pointer)
              OpenAD_Symbol_143 = 1
              do while (INT(OpenAD_Symbol_143).LE.INT(OpenAD_Symbol_142)
     +)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_212 = integer_tape(integer_tape_pointer)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_213 = integer_tape(integer_tape_pointer)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_214 = integer_tape(integer_tape_pointer)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_215 = integer_tape(integer_tape_pointer)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_216 = integer_tape(integer_tape_pointer)
                integer_tape_pointer = integer_tape_pointer-1
                OpenAD_Symbol_217 = integer_tape(integer_tape_pointer)
                X(INT(OpenAD_Symbol_217))%d = X(INT(OpenAD_Symbol_217))%
     +d+SFLD(INT(OpenAD_Symbol_216),INT(OpenAD_Symbol_215),INT(OpenAD_Sy
     +mbol_214),INT(OpenAD_Symbol_213),INT(OpenAD_Symbol_212))%d*(4.0D00
     +)
                SFLD(INT(OpenAD_Symbol_216),INT(OpenAD_Symbol_215),INT(O
     +penAD_Symbol_214),INT(OpenAD_Symbol_213),INT(OpenAD_Symbol_212))%d
     + = 0.0d0
                X(INT(OpenAD_Symbol_217))%d = X(INT(OpenAD_Symbol_217))%
     +d+TFLD(INT(OpenAD_Symbol_216),INT(OpenAD_Symbol_215),INT(OpenAD_Sy
     +mbol_214),INT(OpenAD_Symbol_213),INT(OpenAD_Symbol_212))%d*(3.0D00
     +)
                TFLD(INT(OpenAD_Symbol_216),INT(OpenAD_Symbol_215),INT(O
     +penAD_Symbol_214),INT(OpenAD_Symbol_213),INT(OpenAD_Symbol_212))%d
     + = 0.0d0
                OpenAD_Symbol_143 = INT(OpenAD_Symbol_143)+1
              END DO
              OpenAD_Symbol_141 = INT(OpenAD_Symbol_141)+1
            END DO
            OpenAD_Symbol_139 = INT(OpenAD_Symbol_139)+1
          END DO
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_209 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_210 = integer_tape(integer_tape_pointer)
          integer_tape_pointer = integer_tape_pointer-1
          OpenAD_Symbol_211 = integer_tape(integer_tape_pointer)
          X(INT(OpenAD_Symbol_211))%d = X(INT(OpenAD_Symbol_211))%d+LOCP
     +RES(INT(OpenAD_Symbol_210),INT(OpenAD_Symbol_209))%d*(2.0D00)
          LOCPRES(INT(OpenAD_Symbol_210),INT(OpenAD_Symbol_209))%d = 0.0
     +d0
          OpenAD_Symbol_137 = INT(OpenAD_Symbol_137)+1
        END DO
        OpenAD_Symbol_135 = INT(OpenAD_Symbol_135)+1
      END DO
          end if
        end subroutine head
